language: node_js
node_js:
   - "8.10"
   - "7"
   - "6.10"

before_install:
   - npm i -g npm@6.4.1

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
